/**
 * Nigeria State → City (towns/cities) → Suburb (areas within that city).
 * Not LGA-based: cities are actual urban centres (e.g. Ibadan, Oyo, Ogbomosho);
 * suburbs are neighbourhoods within each city (e.g. Bodija, Oluyole in Ibadan).
 */

export type StateCitiesSuburbs = Record<string, Record<string, string[]>>;

export const NIGERIA_STATE_CITY_SUBURBS: StateCitiesSuburbs = {
  Abia: {
    Aba: ['Ariaria', 'Ogbor Hill', 'Umungasi', 'Asa Nnentu', 'Eziukwu', 'Ehere', 'Obohia', 'Ohanku', 'Abayi', 'Osisioma'],
    'Umuahia': ['Umudike', 'Ohokobe', 'Ibeku', 'Afugiri', 'Oboro', 'Olokoro', 'Ubakala', 'Ezimba'],
    Arochukwu: ['Arochukwu', 'Abam', 'Ihechiowa', 'Ututu'],
    Ohafia: ['Ohafia', 'Abiriba', 'Nkporo'],
    Isuikwuato: ['Isuikwuato', 'Imenyi', 'Orient'],
  },
  Adamawa: {
    Yola: ['Jimeta', 'Doubeli', 'Ribadu', 'Alkalawa', 'Numan Road', 'Yolde Pate', 'Girei'],
    Mubi: ['Mubi Town', 'Vimtim', 'Gella', 'Lainde'],
    Numan: ['Numan Town', 'Lau'],
    Ganye: ['Ganye', 'Sugu', 'Gangumi'],
    Michika: ['Michika', 'Bazza', 'Dulwa'],
    Hong: ['Hong', 'Gaya'],
    Gombi: ['Gombi', 'Boga'],
    Song: ['Song', 'Dirma'],
  },
  'Akwa Ibom': {
    Uyo: ['Ewet', 'Housing Estate', 'Osongama', 'Nwaniba', 'Oron Road', 'Itam', 'Ntak Inyang', 'Four Towns'],
    'Ikot Ekpene': ['Ikot Ekpene Town', 'Urua Inyang', 'Four Towns', 'Abak'],
    Eket: ['Eket Town', 'Ibeno', 'Esit Eket', 'Ntak Inyang'],
    Oron: ['Oron Town', 'Urue Offong', 'Oruko', 'Uya Oron'],
    Etinan: ['Etinan Town', 'Ndon Eyo'],
    Abak: ['Abak Town', 'Ediene'],
  },
  Anambra: {
    Awka: ['Ezinano', 'Amawbia', 'Okpuno', 'Ifite', 'Umudioka', 'Nise', 'Mbaukwu'],
    Onitsha: ['GRA', 'Fegge', 'Odoakpu', 'Woliwo', 'Main Market', 'Bridge Head', 'Harbour'],
    Nnewi: ['Otolo', 'Uruagu', 'Umudim', 'Nnewichi', 'Nnewi Town'],
    Ekwulobia: ['Ekwulobia', 'Igboukwu', 'Akpo'],
    Nnobi: ['Nnobi', 'Alor', 'Nnokwa', 'Oba'],
    Ogidi: ['Ogidi', 'Oraukwu', 'Abatete', 'Nkpor', 'Obosi'],
    Ihiala: ['Ihiala Town', 'Okija', 'Lilu'],
    Aguleri: ['Aguleri', 'Nando', 'Otuocha'],
  },
  Bauchi: {
    Bauchi: ['GRA', 'Yelwa', 'Fadaman Mada', 'Dass Road', 'Wunti', 'Railway', 'Kachi', 'Kudai'],
    Azare: ['Azare Town', 'Katagum'],
    Misau: ['Misau Town', 'Dambam'],
    Ningi: ['Ningi Town', 'Burra'],
    "Jama'are": ["Jama'are Town", 'Itas'],
  },
  Bayelsa: {
    Yenagoa: ['Kpansia', 'Biogbolo', 'Ekeki', 'Ovom', 'Agudama', 'Amarata', 'Swali', 'Okutukutu', 'Opolo', 'Edepie', 'Azikoro'],
    Oporoma: ['Oporoma', 'Sagbama', 'Toru-Orua'],
    Nembe: ['Nembe Town', 'Bassambiri', 'Ogbolomabiri'],
    Brass: ['Brass Town', 'Twon-Brass', 'Okpoama'],
    Oloibiri: ['Oloibiri', 'Kolo', 'Emeyal'],
  },
  Benue: {
    Makurdi: ['Wurukum', 'High Level', 'North Bank', 'Wadata', 'Ankpa', 'Kanshio', 'Modern Market', 'GRA', 'Idah', 'Fiidi'],
    Gboko: ['Gboko Town', 'Wannune', 'Mbakor', 'Mbaav', 'Mbatyerev'],
    Otukpo: ['Otukpo Town', 'Upu', 'Adoka', 'Ochobo'],
    'Katsina-Ala': ['Katsina-Ala Town', 'Zaki Biam', 'Tor Donga'],
    Adikpo: ['Adikpo', 'Turan', 'Ikurav'],
    Vandeikya: ['Vandeikya Town', 'Mbakya', 'Mbaya'],
    Aliade: ['Aliade', 'Ushongo'],
    Naka: ['Naka', 'Aondoana'],
  },
  Borno: {
    Maiduguri: ['GRA', 'Bulabulin', 'Gwange', 'Bolori', 'Lamido', 'Maisandari', 'Customs', 'Monday Market', 'Baga Road', 'Damboa Road', 'Bulumkutu', 'Jajeri', 'Muna'],
    Bama: ['Bama Town', 'Banki', 'Gwoza'],
    Biu: ['Biu Town', 'Shani', 'Kwaya'],
    Dikwa: ['Dikwa Town', 'Gamboru', 'Ngala'],
    Gwoza: ['Gwoza Town', 'Pulka', 'Hambagda', 'Limankara'],
    Konduga: ['Konduga Town', 'Bama', 'Mafa'],
  },
  'Cross River': {
    Calabar: ['Efio-Etung', 'Etta Agbor', 'Atimbo', '8 Miles', 'Marian', 'State Housing', 'Parliamentary', 'Eden', 'Goldie', 'Mount Zion', 'New Airport', 'Anantigha', 'Twin Creek', 'Henshaw Town', 'New Town', 'Duke Town', 'Creek Town', 'Old Town'],
    Ogoja: ['Ogoja Town', 'Mbube', 'Ekajuk', 'Nkum'],
    Ikom: ['Ikom Town', 'Nde', 'Abanyom', 'Nnam'],
    Obudu: ['Obudu Town', 'Bebi', 'Obudu Ranch'],
    Ugep: ['Ugep', 'Ekori', 'Nko'],
    Oron: ['Oron Town', 'Urue Offong'],
  },
  Delta: {
    Asaba: ['GRA', 'Cable Point', 'Nnebisi Road', 'DBS', 'Summit', 'Okpanam Road', 'Infantry', 'Jesus Saves', 'Anwai', 'Ibusa', 'Okwe', 'Akwukwu-Igbo'],
    Warri: ['GRA', 'Effurun', 'Ekpan', 'Ugbomro', 'Ugborikoko', 'Pessu', 'Edjeba', 'Igbudu', 'Okere', 'Ogunu', 'Osubi', 'Ubeji', 'Ifie', 'DSC', 'PTI', 'Enerhen', 'Jakpa'],
    Sapele: ['Sapele Town', 'Amuokpe', 'Elume', 'Koko'],
    Ughelli: ['Ughelli Town', 'Otor-Ughelli', 'Agbarho', 'Evwreni'],
    Agbor: ['Agbor', 'Boji-Boji', 'Alihame', 'Owa'],
    Ozoro: ['Ozoro', 'Oleh', 'Owhelogbo'],
    Kwale: ['Kwale', 'Utagba-Uno', 'Ossissa', 'Aboh', 'Ashaka'],
    Oleh: ['Oleh', 'Ozoro', 'Uzere', 'Enwhe'],
  },
  Ebonyi: {
    Abakaliki: ['Presco', 'Water Works', 'Kpirikpiri', 'Hausa Quarter', 'Nkaliki', 'Ezza Road', 'Ogoja Road', 'Afikpo Road', 'GRA'],
    Afikpo: ['Afikpo Town', 'Ndibe', 'Amasiri', 'Unwana'],
    Onueke: ['Onueke', 'Ezza', 'Ishieke'],
    Ishiagu: ['Ishiagu', 'Ivo'],
  },
  Edo: {
    'Benin City': ['GRA', 'Ring Road', 'Sapele Road', 'Akpakpava', 'Ugbowo', 'Uselu', 'Siluko', 'New Benin', 'Ogida', 'Ikpoba Hill', 'Oregbeni', 'Ekehuan', 'Ekenwan', 'Ugbekun', 'Idogbo', 'Adolor'],
    Auchi: ['Auchi Town', 'Jattu', 'Afuze', 'Igarra'],
    Ekpoma: ['Ekpoma', 'Irrua', 'Ujemen'],
    Uromi: ['Uromi', 'Ubiaja', 'Irrua'],
    Agenebode: ['Agenebode', 'Weppa'],
  },
  Ekiti: {
    'Ado Ekiti': ['GRA', 'Odo Ado', 'Okeyinmi', 'Ijigbo', 'Atikankan', 'Oja Oba', 'Basiri', 'Fajuyi', 'Olorunda', 'Idolofin'],
    Ikere: ['Ikere Town', 'Ikere Ekiti', 'Igbara Odo'],
    Ikole: ['Ikole Town', 'Odo Ayedun', 'Ijesa Isu'],
    Ijero: ['Ijero Town', 'Ipoti', 'Aramoko'],
    Oye: ['Oye Town', 'Ilupeju', 'Ayegbaju'],
    Aramoko: ['Aramoko', 'Igede', 'Erinjiyan'],
    Ise: ['Ise Ekiti', 'Orun Ekiti'],
  },
  Enugu: {
    Enugu: ['GRA', 'Independence Layout', 'New Haven', 'Abakpa', 'Trans Ekulu', 'Emene', 'Thinkers Corner', 'Ogbete', 'Ogui New Layout', 'Uwani', 'Achara Layout', 'Idaw River', 'Nkwo', 'Emene'],
    Nsukka: ['Nsukka Town', 'University of Nigeria', 'Opi', 'Ede Oballa', 'Obukpa', 'Eha Alumona', 'Orba', 'Ibagwa'],
    Oji: ['Oji Town', 'Achi', 'Inyi'],
    Agbani: ['Agbani', 'Amurri', 'Obe'],
    Udi: ['Udi Town', 'Ngwo', 'Eke', 'Obinagu'],
    Obollo: ['Obollo Afor', 'Orba', 'Imilike'],
  },
  FCT: {
    Abuja: [
      'Maitama', 'Garki', 'Garki 2', 'Wuse', 'Wuse 2', 'Gwarinpa', 'Kubwa', 'Lugbe', 'Karu', 'Nyanya',
      'Mabushi', 'Jabi', 'Utako', 'Kado', 'Katampe', 'Life Camp', 'Gaduwa', 'Lokogoma', 'Central Area',
      'Asokoro', 'Guzape', 'Guzape II', 'Wuye', 'Dutse', 'Apo', 'Gudu', 'Kaura', 'Kado Estate',
      'Gwarinpa Estate', 'Kubwa Village', 'Lugbe Village', 'Karshi', 'Kuje', 'Kurudu', 'Orozo', 'Karsana',
      'Central Business District', 'CBD', 'Wuye', 'Utako', 'Jahi', 'Kukwaba', 'Dakibiyu', 'Duboyi',
      'Durumi', 'Gaduwa', 'Gwarinpa', 'Jabi', 'Karmo', 'Katampe', 'Kaura', 'Lokogoma', 'Mabushi',
      'Nbora', 'Wumba', 'Wupa', 'Apo-Dutse', 'Kabusa', 'Gwagwalada Town', 'Kwali', 'Bwari',
    ],
    Bwari: ['Bwari Town', 'Ushafa', 'Shere', 'Kuduru', 'Byazhin', 'Dutse'],
    Gwagwalada: ['Gwagwalada Town', 'Kwali', 'Dobi', 'Paiko', 'Tunga Maje'],
    Kuje: ['Kuje Town', 'Kabi', 'Gwargwada', 'Ruben', 'Chibiri'],
    Kwali: ['Kwali Town', 'Yangoji', 'Pai', 'Gumbo'],
  },
  Gombe: {
    Gombe: ['GRA', 'Tudun Wada', 'Herwagana', 'Bolari', 'Nassarawo', 'Jekadafari', 'Pantami', 'Madaki', 'Sabon Layi', 'Gombe Aba', 'Kumbo', 'Doma'],
    Kumo: ['Kumo', 'Pindiga'],
    Bajoga: ['Bajoga', 'Dadin Kowa'],
    Billiri: ['Billiri Town', 'Kaltungo', 'Tangale'],
    Dukku: ['Dukku Town', 'Wawa'],
  },
  Imo: {
    Owerri: ['Aladinma', 'Ikenegbu', 'Douglas', 'Wetheral', 'New Owerri', 'World Bank', 'Amakohia', 'Orogwe', 'Orji', 'Nekede', 'Eziobodo', 'Ihiagwa', 'Naze', 'Egbu'],
    Orlu: ['Orlu Town', 'Amaifeke', 'Eziachi', 'Ihite', 'Umuna'],
    Okigwe: ['Okigwe Town', 'Umulolo', 'Ezinachi', 'Lowa'],
    Mgbidi: ['Mgbidi', 'Awo Idemili', 'Omuma'],
    Oguta: ['Oguta Town', 'Egbema', 'Ohaji'],
    Nkwerre: ['Nkwerre Town', 'Orlu', 'Umudi'],
  },
  Jigawa: {
    Dutse: ['Dutse Town', 'GRA', 'Sakwaya', 'Kachi', 'Kudai', 'Chamo'],
    Hadejia: ['Hadejia Town', 'Auyo', 'Kiri Kasama'],
    Kazaure: ['Kazaure Town', 'Roni', 'Gwiwa'],
    Gumel: ['Gumel', 'Garki'],
    'Birnin Kudu': ['Birnin Kudu Town', 'Garko'],
  },
  Kaduna: {
    Kaduna: ['Malali', 'Ungwan Rimi', 'Kawo', 'Doka', 'Sabon Gari', 'Hayin Banki', 'Barnawa', 'Kakuri', 'Narayi', 'Ungwan Sanusi', 'Tudun Wada', 'Sabon Tasha'],
    Zaria: ['Zaria Town', 'Samaru', 'Tudun Wada', 'Sabon Gari', 'Hanwa', 'Kongola', 'PZ', 'Gaskiya', 'GRA', 'Nuhu Bamalli', 'Kofan Gayan', 'Kofan Doka'],
    Kafanchan: ['Kafanchan Town', 'Kagarko', 'Kajuru'],
    Kachia: ['Kachia Town', 'Kajuru'],
    'Birnin Gwari': ['Birnin Gwari Town', 'Kuyello'],
  },
  Kano: {
    Kano: ['Fagge', 'Dala', 'Gwale', 'Nassarawa', 'Tarauni', 'Ungogo', 'Kumbotso', 'GRA', "Sabon Gari", "Noman's Land", 'Hotoro', 'Sharada', 'Tudun Wada', 'Kano Municipal', 'Challawa'],
    Wudil: ['Wudil Town', 'Gaya'],
    Gaya: ['Gaya Town', 'Wudil', 'Gezawa'],
    'Dawakin Tofa': ['Dawakin Tofa Town', 'Tofa'],
    Gwarzo: ['Gwarzo Town', 'Dawakin Tofa'],
    Bichi: ['Bichi Town', 'Dawakin Tofa'],
  },
  Katsina: {
    Katsina: ['GRA', 'Sabuwar Ungu', 'Yankara', 'Dutsin Ma Road', 'Kofar Sauri', 'Kofar Marusa', 'Kofar Durbi', 'Kofar Yandaka'],
    Funtua: ['Funtua Town', 'Faskari', 'Dandume', 'Bakori', 'Malumfashi'],
    'Dutsin Ma': ['Dutsin Ma Town', 'Kurfi', 'Safana'],
    Daura: ['Daura Town', 'Zango', "Mai'Adua"],
    Malumfashi: ['Malumfashi Town', 'Kafur'],
    Kankara: ['Kankara Town', 'Funtua'],
  },
  Kebbi: {
    'Birnin Kebbi': ['Birnin Kebbi Town', 'GRA', 'Nassarawa', 'Gesse', 'Sauri', 'Kangiwa', 'Danko'],
    Zuru: ['Zuru Town', 'Fakai', 'Danko'],
    Yauri: ['Yauri Town', 'Ngaski'],
    Argungu: ['Argungu Town', 'Augie'],
    Jega: ['Jega Town', 'Aleiro'],
  },
  Kogi: {
    Lokoja: ['GRA', 'Lokoja Town', 'Adankolo', 'Lugard', 'Ganaja', 'Koton Karfe', 'Felele', 'Zango', 'Cantoment'],
    Okene: ['Okene Town', 'Okehi', 'Adavi', 'Ajaokuta'],
    Idah: ['Idah Town', 'Ibaji'],
    Kabba: ['Kabba Town', 'Bunu', 'Okehi'],
    Ankpa: ['Ankpa Town', 'Olamaboro', 'Omala'],
    Ogugu: ['Ogugu', 'Olamaboro'],
  },
  Kwara: {
    Ilorin: ['GRA', 'Tanke', 'Sango', 'Oja Iya', 'Pakata', 'Adewole', 'Zango', 'Kulende', 'Unity', 'Oloje', 'Ita Amodu', 'Oko Erin', 'Oko Oba', 'Oke Oyi', 'Oke Ose', 'Gaa Akanbi', 'Fufu', 'Ojoku'],
    Offa: ['Offa Town', 'Ilemona', 'Erin Ile'],
    'Omu Aran': ['Omu Aran', 'Arandun', 'Oko'],
    Lafiagi: ['Lafiagi', 'Tsaragi', 'Pategi'],
    Kaiama: ['Kaiama Town', 'Baruten'],
  },
  Lagos: {
    Ikeja: [
      'Allen Avenue', 'Opebi', 'Ikeja GRA', 'Alausa', 'Ogba', 'Oregun', 'Adeniyi Jones', 'Oba Akran',
      'Ajao Estate', 'Ojodu', 'Maryland', 'Anthony', 'Palmgrove', 'GRA Ikeja', 'Opebi Link', 'Simpson',
      'Awolowo Way', 'Ikeja City Mall', 'Oba Akran Avenue', 'Bank Anthony Way', 'Kodesoh', 'Adeniyi Jones Avenue',
      'Opebi Road', 'Allen Junction', 'Opebi-Oregun', 'Ojodu Berger', 'Ikeja Under Bridge', 'Computer Village',
    ],
    'Lagos Island': [
      'Marina', 'Isale Eko', 'Idumota', 'Obalende', 'Tinubu', 'Broad Street', 'Nnamdi Azikiwe', 'Balogun',
      'Lagos Island', 'CMS', 'Adeniji Adele', 'Epetedo', 'Lafiaji', 'Oluwole', 'Eko Idumota', 'Sand Grouse',
    ],
    'Victoria Island': [
      'VI', 'Oniru', 'Osborne', 'Dolphin', 'Idado', 'Ahmadu Bello Way', 'Admiralty Way', 'Ozumba Mbadiwe',
      'Adeola Odeku', 'Sanusi Fafunwa', 'Bishop Oluwole', 'Oniru Estate', 'Maroko', 'Waterfront',
    ],
    Ikoyi: [
      'Ikoyi', 'Ikoyi GRA', 'Bourdillon', 'Gerrard Road', 'Glover Road', 'Alfred Rewane', 'Queen Drive',
      'Parkview', 'Lugard Avenue', 'Ribadu Road', 'Thompson Avenue', 'Osborne Road', 'Ikoyi Club',
    ],
    Lekki: [
      'Lekki Phase 1', 'Lekki Phase 2', 'Chevron', 'Admiralty Way', 'Osapa', 'Osapa London', 'Jakande',
      'Ikota', 'VGC', 'Maroko', 'Ilasan', 'Lekki Epe Expressway', 'Orchid Road', 'Fola Osibo', 'Ologolo',
      'Ikate', 'Sangotedo', 'Ajah', 'Awoyaya', 'Lakowe', 'Abijo', 'Eleko', 'Ibeju Lekki',
    ],
    Ajah: ['Ajah', 'Sangotedo', 'Awoyaya', 'Lekki', 'Badore', 'Ado', 'Langbasa', 'Ikate Elegushi'],
    Surulere: [
      'Adeniran Ogunsanya', 'Bode Thomas', 'Ijeshatedo', 'Itire', 'Coker', 'Aguda', 'Ojuelegba',
      'Stadium', 'Lawanson', 'Ogunlana', 'Adelabu', 'Shitta', 'Orile Surulere', 'Animashaun', 'Adeniyi Jones',
    ],
    Yaba: [
      'Yaba', 'Ebute Metta', 'Iddo', 'Oyingbo', 'Jibowu', 'Fadeyi', 'Bariga', 'Palmgrove', 'Shomolu',
      'Akoka', 'Sabon Yaba', 'Fadipe', 'Iwaya', 'Makoko', 'Alagomeji', 'Tejuosho',
    ],
    Agege: [
      'Agege Town', 'Oko Oba', 'Papa Ashafa', 'Orile Agege', 'Tabon Tabon', 'Iju', 'Ishaga', 'Abule Egba',
      'Obawole', 'Fagba', 'Alakuko', 'Oke Koto', 'Isale Oja', 'Papa Ashafa',
    ],
    Ikorodu: [
      'Ikorodu Town', 'Sagamu Road', 'Ebute', 'Igbogbo', 'Ipakodo', 'Owutu', 'Agbowa', 'Imota',
      'Ikorodu West', 'Ikorodu North', 'Odogunyan', 'Ita Elewa', 'Lagos Road', 'Ikorodu GRA',
    ],
    Alimosho: [
      'Egbeda', 'Idimu', 'Igando', 'Ikotun', 'Shasha', 'Akowonjo', 'Ayobo', 'Ipaja', 'Ejigbo',
      'Abule Egba', 'Orile', 'Alimosho', 'Pleasure', 'Command', 'Oke Afa', 'Isolo', 'Akowonjo Roundabout',
    ],
    Ojo: [
      'Ojo Town', 'Alaba', 'Iba', 'Okokomaiko', 'Trade Fair', 'Satellite', 'Volkswagen', 'Ijanikin',
      'Festac', 'Mile 2', 'Alaba International', 'Ojo Barracks', 'Iba Estate', 'Liya',
    ],
    Badagry: ['Badagry Town', 'Ajara', 'Topo', 'Gberefu', 'Iworo', 'Ikoga', 'Apa', 'Seme', 'Agbara'],
    Epe: ['Epe Town', 'Lekki', 'Oriba', 'Odomola', 'Poka', 'Ogunmo', 'Epe Division'],
    Apapa: ['Apapa GRA', 'Ijora', 'Kirikiri', 'Lily Pond', 'Marine Beach', 'Tin Can', 'Olodan'],
    Mushin: ['Mushin', 'Ladipo', 'Odi Olowo', 'Babalosa', 'Papa Ajao', 'Ojuwoye', 'Alakara', 'Idi Oro'],
    Oshodi: ['Oshodi', 'Isolo', 'Shogunle', 'Mafoluku', 'Ilasamaja', 'Ajao Estate'],
  },
  Nasarawa: {
    Lafia: ['Lafia Town', 'GRA', 'Makurdi Road', 'Obi', 'Shabu', 'Adogi'],
    Keffi: ['Keffi Town', 'New Karu'],
    Karu: ['Karu Town', 'Mararaba', 'One Man Village', 'Karshi', 'Jikwoyi', 'Kurudu', 'Orozo', 'Ado'],
    Akwanga: ['Akwanga Town'],
    Nasarawa: ['Nasarawa Town'],
    Wamba: ['Wamba Town'],
  },
  Niger: {
    Minna: ['Minna Town', 'GRA', 'Tunga', 'Kpakungu', 'Dutsen Kura', 'Gwari', 'Maikunkele', 'Bosso'],
    Bida: ['Bida Town', 'GRA', 'Nasarawa', 'Lemu'],
    Suleja: ['Suleja Town', 'Abuja Road'],
    Kontagora: ['Kontagora Town', 'Mariga', 'Mashegu'],
    'New Bussa': ['New Bussa', 'Wawa', 'Kainji'],
    Lapai: ['Lapai Town', 'Agaie'],
  },
  Ogun: {
    Abeokuta: ['GRA', 'Ibara', 'Kuto', 'Adatan', 'Isale Igbein', 'Sapon', 'Ita Eko', 'Lafenwa', 'Oke Ilewo', 'Camp', 'Olomore', 'Oke Lantoro', 'Ake', 'Itoku', 'Imeko'],
    Sagamu: ['Sagamu Town', 'Makun', 'Ikenne'],
    'Ijebu Ode': ['Ijebu Ode Town', 'Obalende', 'Ita Osun'],
    Ota: ['Ota Town', 'Sango', 'Agbara', 'Ado-Odo'],
    Ilaro: ['Ilaro Town', 'Ota'],
    Mowe: ['Mowe', 'Ofada', 'Ibafo', 'Magboro', 'Ajura'],
    Ikenne: ['Ikenne Town', 'Remo'],
    Ayetoro: ['Ayetoro', 'Igbogila'],
  },
  Ondo: {
    Akure: ['Akure Town', 'Oda Road', 'Alagbaka', 'Oba Ile', 'Onyearugbulem', 'Shasha', 'Oke Aro', 'Iyere', 'Futa Road', 'Ondo Road'],
    Ondo: ['Ondo Town', 'Ondo West', 'Ondo East'],
    Ore: ['Ore Town', 'Odigbo'],
    Owo: ['Owo Town', 'Ipele'],
    Okitipupa: ['Okitipupa Town', 'Igbotako'],
    Ikare: ['Ikare', 'Oka', 'Arigidi'],
    Oka: ['Oka', 'Akungba'],
    Igbokoda: ['Igbokoda', 'Ugbo'],
  },
  Osun: {
    Osogbo: ['GRA', 'Oke Baale', 'Oja Oba', 'Oke Fia', 'Isale Osun', 'Olorunsogo', 'Oke Ayepe', 'Dagbolu', 'Ota Efun', 'Lameco', 'Ogo Oluwa', 'Alekuwodo', 'Oke Oniti', 'Testing Ground'],
    'Ile-Ife': ['Ile Ife', 'Modakeke', 'OAU', 'Mayfair', 'Oke Ogbo', 'Enuwa', 'Ipetumodu', 'Ifetedo'],
    Ilesa: ['Ilesa Town', 'Ereja', 'Okesa', 'Irojo'],
    Ede: ['Ede Town', 'Ede North', 'Ede South'],
    Iwo: ['Iwo Town'],
    Ikirun: ['Ikirun Town'],
    Ejigbo: ['Ejigbo Town'],
    'Ila Orangun': ['Ila Orangun'],
    Gbongan: ['Gbongan'],
    Ikire: ['Ikire'],
  },
  Oyo: {
    Ibadan: [
      'Jericho', 'Jericho GRA', 'Bodija', 'Bodija Market', 'Agodi', 'Agodi GRA', 'Agodi Gardens',
      'Oluyole', 'Oluyole Estate', 'Eleyele', 'Elebu', 'UI', 'Agbowo', 'Mokola', 'Ring Road', 'Mobil',
      'Challenge', 'Molete', 'Apata', 'Ologuneru', 'Olodo', 'Omi Adio', 'Oke Ado', 'Oke Bola', 'Oke Padre',
      'Mapo', 'Beere', 'Orita Challenge', 'Oritamefa', 'Orogun', 'Sango', 'Gate', 'Idi Ayunre', 'Odo Ona',
      'Dugbe', 'Oja Oba', 'Yemetu', 'Akobo', 'New Garage', 'Samonda', 'Iyaganku', 'Iyaganku GRA',
      'Onika GRA', 'Idi-Ape', 'Monatan', 'Ikolaba', 'Iwo Road', 'Oke Bola', 'Oke Aremo', 'Oke Offa',
      'Oke Fia', 'Oke Are', 'Oke Itunu', 'Oke Seni', 'Oke Ado', 'Oke Padre', 'Oke Ogunpa', 'Oke Iwo',
      'Oritamefa', 'Orogun', 'Awolowo', 'Total Garden', 'Akinyele', 'Ojo', 'Moniya', 'Olodo',
      'Eleyele', 'Omi Adio', 'Apata', 'Idi Ayunre', 'Olorunda', 'Egbeda', 'Lagelu', 'Lalupon',
      'Olorunsogo', 'Akanran', 'Ona Ara', 'Olomi', 'Orisunbare', 'Alakia', 'Adelabu', 'Oke Itunu',
      'Basorun', 'Bashorun', 'Felele', 'Odo Ona', 'Odo Oba', 'Adegbayi', 'Olunde', 'Ojoo',
      'UI Road', 'Queen Elizabeth Road', 'Liberty Road', 'Awolowo Road', 'Oritamefa', 'Poly Road',
    ],
    Oyo: ['Oyo Town', 'Oyo East', 'Oyo West', 'Fiditi', 'Jobele', 'Awe', 'Atiba', 'Oyo GRA'],
    Ogbomosho: ['Ogbomosho Town', 'Ogbomosho North', 'Ogbomosho South'],
    Fiditi: ['Fiditi', 'Jobele', 'Afijio'],
    Iseyin: ['Iseyin Town'],
    Saki: ['Saki Town', 'Saki East', 'Saki West'],
    Eruwa: ['Eruwa', 'Lanlate', 'Ibarapa'],
    Okeho: ['Okeho', 'Kajola'],
    Kisi: ['Kisi', 'Irepo'],
    Igbeti: ['Igbeti', 'Olorunsogo'],
    Ilero: ['Ilero', 'Orelope'],
    'Igbo Ora': ['Igbo Ora', 'Ibarapa Central'],
    Ayete: ['Ayete', 'Ibarapa North'],
    Tede: ['Tede', 'Atisbo'],
    'Iwere Ile': ['Iwere Ile', 'Iwajowa'],
  },
  Plateau: {
    Jos: ['Jos Town', 'Terminus', 'Bukuru', 'Rayfield', 'GRA', 'Rukuba', 'Naraguta', 'Bauchi Road', 'Mado', 'Angwan Rukuba'],
    Bukuru: ['Bukuru', 'Vom', 'Kuru'],
    Pankshin: ['Pankshin Town'],
    Langtang: ['Langtang', 'Langtang North', 'Langtang South'],
    Shendam: ['Shendam Town'],
    Mangu: ['Mangu Town'],
    Dengi: ['Dengi', 'Kanam'],
  },
  Rivers: {
    'Port Harcourt': [
      'GRA', 'Rumuola', 'Rumuomasi', 'Rumuokoro', 'Trans Amadi', 'Woji', 'Rumuepirikom', 'Rumuigbo',
      'Eliozu', 'Ozuoba', 'Choba', 'Aluu', 'Rukpokwu', 'Eneka', 'Rumuodara', 'Mgbousimini', 'Rumukalagbor',
      'Abuloma', 'Mile 1', 'Mile 2', 'Mile 3', 'Mile 4', 'D/Line', 'Old GRA', 'New GRA', 'Borokiri',
      'Diobu', 'Ogbunabali', 'Elekahia', 'Rumola', 'Rumuekini', 'Ozuoba', 'Rumuola', 'Rumola',
      'Abuloma', 'Rumukalagbor', 'Rumuola', 'Eliozu', 'Ozuoba', 'Choba', 'Aluu', 'Rukpokwu',
      'Eneka', 'Rumuodara', 'Mgbousimini', 'Rumukalagbor', 'Mile 1 Diobu', 'Mile 2', 'Mile 3', 'Mile 4',
      'Aba Road', 'Aba Expressway', 'East West Road', 'Peter Odili Road', 'Olumeni', 'Oroworukwo',
    ],
    Oyigbo: ['Oyigbo Town', 'Afam', 'Kom Kom', 'Creek Road', 'Oyigbo'],
    Eleme: ['Nchia', 'Onne', 'Refinery'],
    Bori: ['Bori', 'Kaani', 'Khana', 'Gokana'],
    Omoku: ['Omoku', 'Egbema', 'Ndoni'],
    Ahoada: ['Ahoada', 'Oyigbo'],
    Bonny: ['Bonny Town', 'Finima'],
    Degema: ['Degema Town'],
    Okrika: ['Okrika Town'],
  },
  Sokoto: {
    Sokoto: ['GRA', 'Runjin Sambo', 'Arkilla', 'Gagi', 'Sultan Bello', 'Mabera', 'Wamakko'],
    Tambuwal: ['Tambuwal Town'],
    Gwadabawa: ['Gwadabawa Town'],
    Illela: ['Illela Town'],
    'Sabon Birni': ['Sabon Birni Town'],
  },
  Taraba: {
    Jalingo: ['Jalingo Town', 'GRA', 'Sunkani', 'Sabon Gari'],
    Wukari: ['Wukari Town'],
    Takum: ['Takum Town'],
    Serti: ['Serti', 'Gashaka'],
    Bali: ['Bali Town'],
    'Mutum Biu': ['Mutum Biu', 'Gassol'],
    Lau: ['Lau Town'],
  },
  Yobe: {
    Damaturu: ['Damaturu Town', 'GRA', 'Pompomari', 'Maisandari', 'Gujba'],
    Potiskum: ['Potiskum Town', 'Fika'],
    Gashua: ['Gashua', 'Bade'],
    Nguru: ['Nguru Town'],
    Geidam: ['Geidam Town'],
    'Buni Yadi': ['Buni Yadi', 'Gujba'],
  },
  Zamfara: {
    Gusau: ['Gusau Town', 'GRA', 'Tudun Wada', 'Sabon Gari'],
    'Kaura Namoda': ['Kaura Namoda Town'],
    'Talata Mafara': ['Talata Mafara Town'],
    Anka: ['Anka Town'],
    Bukkuyum: ['Bukkuyum Town'],
  },
};

/** All cities for a state. Use for dropdowns when API is unavailable or to merge with DB. */
export function getCitiesForState(state: string): string[] {
  const map = NIGERIA_STATE_CITY_SUBURBS[state];
  if (!map) return [];
  return Object.keys(map).sort((a, b) => a.localeCompare(b));
}

/** All suburbs for a state+city. Use for dropdowns when API is unavailable or to merge with DB. */
export function getSuburbsForCity(state: string, city: string): string[] {
  const stateMap = NIGERIA_STATE_CITY_SUBURBS[state];
  if (!stateMap) return [];
  const suburbs = stateMap[city];
  if (!suburbs) return [];
  return [...new Set(suburbs)].sort((a, b) => a.localeCompare(b));
}
