'use client';

import { useSession } from 'next-auth/react';
import Link from 'next/link';
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { useEffect, useMemo, useRef, useState } from 'react';
import { LISTING_TYPE } from '@/lib/constants';
import { toFirstName } from '@/lib/display-name';
import type { PublicCreatedBy } from '@/lib/verification';

type OfferRow = {
  _id: string;
  amount: number;
  status: string;
  turn: string;
  listingPriceAtCreate: number;
  maintainAmount?: number;
  sellerCounterLocked?: boolean;
  createdAt?: string;
  updatedAt?: string;
  buyer: PublicCreatedBy | null;
};

type OffersPayload = {
  offersEnabled: boolean;
  listingPrice: number;
  offers: OfferRow[];
};

type BuyerOfferDetails = {
  legalName: string;
  email: string;
  phone: string;
  address: string;
  completionTimeline: string;
  additionalTerms: string;
};

function formatNgn(n: number) {
  return new Intl.NumberFormat('en-NG', { style: 'currency', currency: 'NGN', maximumFractionDigits: 0 }).format(n);
}

function truncatePlainText(input: string, maxLen: number) {
  const normalized = input.replace(/\s+/g, ' ').trim();
  if (normalized.length <= maxLen) return normalized;
  return `${normalized.slice(0, Math.max(0, maxLen - 3)).trim()}...`;
}

function buildProfessionalOfferDraft({
  buyer,
  propertyType,
  listingTitle,
  propertyDescription,
  propertyLocation,
  askingPrice,
  offerAmount,
}: {
  buyer: BuyerOfferDetails;
  propertyType: string;
  listingTitle: string;
  propertyDescription: string;
  propertyLocation: string;
  askingPrice: number;
  offerAmount: number | null;
}) {
  const normalizedPropertyType = propertyType.trim() || 'property';
  const normalizedTitle = listingTitle.trim() || '[Property title]';
  const normalizedDescription = truncatePlainText(propertyDescription, 220) || '[Property description]';
  const normalizedLocation = propertyLocation.trim() || '[Property location]';
  const normalizedBuyerName = buyer.legalName.trim() || '[Buyer legal name]';
  const normalizedBuyerEmail = buyer.email.trim() || '[Buyer email]';
  const normalizedBuyerPhone = buyer.phone.trim() || '[Buyer phone]';
  const normalizedBuyerAddress = buyer.address.trim() || '[Buyer address]';
  const amountLine = offerAmount && offerAmount > 0 ? formatNgn(offerAmount) : '[Insert offer amount]';
  const completionTimeline = buyer.completionTimeline.trim() || '[Insert timeline]';
  const additionalTerms = buyer.additionalTerms.trim() || '[Insert financing/deposit/special conditions]';

  const draft = [
    `RE: Professional Purchase Offer for ${normalizedTitle}`,
    '',
    `Buyer Legal Name: ${normalizedBuyerName}`,
    `Buyer Email: ${normalizedBuyerEmail}`,
    `Buyer Phone: ${normalizedBuyerPhone}`,
    `Buyer Address: ${normalizedBuyerAddress}`,
    `Property Type: ${normalizedPropertyType}`,
    `Property Description: ${normalizedDescription}`,
    `Property Location: ${normalizedLocation}`,
    `Asking Price: ${formatNgn(askingPrice)}`,
    `Proposed Purchase Price: ${amountLine}`,
    '',
    'Dear Seller,',
    `I hereby submit this professional offer to purchase the above ${normalizedPropertyType}.`,
    'This offer is subject to satisfactory due diligence, title verification, and execution of a mutually agreed sale agreement.',
    '',
    `Preferred Completion Timeline: ${completionTimeline}`,
    `Additional Terms: ${additionalTerms}`,
    '',
    'Kindly review and respond to this offer at your earliest convenience.',
    '',
    'Signed,',
    normalizedBuyerName,
  ].join('\n');

  return draft.length > 1000 ? `${draft.slice(0, 997).trimEnd()}...` : draft;
}

export function ProfessionalOffersPanel({
  listingId,
  listingType,
  isOwner,
  listingTitle,
  propertyType,
  listingDescription,
  locationDisplay,
}: {
  listingId: string;
  listingType: string;
  isOwner: boolean;
  listingTitle: string;
  propertyType: string;
  listingDescription: string;
  locationDisplay: string;
}) {
  const { data: session, status } = useSession();
  const queryClient = useQueryClient();
  const [amountInput, setAmountInput] = useState('');
  const [messageInput, setMessageInput] = useState('');
  const [buyerDetails, setBuyerDetails] = useState<BuyerOfferDetails>({
    legalName: '',
    email: '',
    phone: '',
    address: '',
    completionTimeline: '',
    additionalTerms: '',
  });
  const [counterByOffer, setCounterByOffer] = useState<Record<string, string>>({});
  const [counterMsgByOffer, setCounterMsgByOffer] = useState<Record<string, string>>({});
  const [showCreateForm, setShowCreateForm] = useState(false);
  const hasAutogeneratedDraft = useRef(false);
  const hasInitializedBuyerDetails = useRef(false);

  const { data, isPending, isError, error, refetch } = useQuery({
    queryKey: ['listing-offers', listingId],
    queryFn: async () => {
      const r = await fetch(`/api/listings/${listingId}/offers`);
      const j = await r.json().catch(() => ({}));
      if (!r.ok) throw new Error(typeof j?.error === 'string' ? j.error : 'Failed to load offers');
      return j as OffersPayload;
    },
    enabled: listingType === LISTING_TYPE.SALE && !!listingId,
  });

  const createOffer = useMutation({
    mutationFn: async () => {
      const amount = Number(String(amountInput).replace(/,/g, ''));
      const legalName = buyerDetails.legalName.trim();
      if (!legalName) {
        throw new Error('Buyer legal name is required');
      }
      const message = (messageInput.trim() || generatedDraft).trim();
      const r = await fetch(`/api/listings/${listingId}/offers`, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          amount,
          message: message || undefined,
        }),
      });
      const j = await r.json().catch(() => ({}));
      if (!r.ok) throw new Error(typeof j?.error === 'string' ? j.error : 'Could not send offer');
      return j;
    },
    onSuccess: () => {
      setAmountInput('');
      setMessageInput('');
      setBuyerDetails((prev) => ({
        ...prev,
        completionTimeline: '',
        additionalTerms: '',
      }));
      hasAutogeneratedDraft.current = false;
      setShowCreateForm(false);
      queryClient.invalidateQueries({ queryKey: ['listing-offers', listingId] });
    },
  });

  const patchOffer = useMutation({
    mutationFn: async ({ offerId, body }: { offerId: string; body: Record<string, unknown> }) => {
      const r = await fetch(`/api/listings/${listingId}/offers/${offerId}`, {
        method: 'PATCH',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify(body),
      });
      const j = await r.json().catch(() => ({}));
      if (!r.ok) throw new Error(typeof j?.error === 'string' ? j.error : 'Update failed');
      return j;
    },
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ['listing-offers', listingId] });
    },
  });

  const negotiatingMine = useMemo(() => {
    if (!data?.offers?.length) return null;
    return data.offers.find((o) => o.status === 'negotiating') ?? null;
  }, [data?.offers]);

  const draftOfferAmount = useMemo(() => {
    const parsed = Number(String(amountInput).replace(/,/g, ''));
    return parsed > 0 ? parsed : null;
  }, [amountInput]);

  const generatedDraft = useMemo(
    () =>
      buildProfessionalOfferDraft({
        buyer: buyerDetails,
        propertyType,
        listingTitle,
        propertyDescription: listingDescription,
        propertyLocation: locationDisplay,
        askingPrice: data?.listingPrice ?? 0,
        offerAmount: draftOfferAmount,
      }),
    [
      buyerDetails,
      propertyType,
      listingTitle,
      listingDescription,
      locationDisplay,
      data?.listingPrice,
      draftOfferAmount,
    ]
  );

  useEffect(() => {
    if (!session || hasInitializedBuyerDetails.current) return;
    setBuyerDetails((prev) => ({
      ...prev,
      legalName: prev.legalName || session.user.name || '',
      email: prev.email || session.user.email || '',
    }));
    hasInitializedBuyerDetails.current = true;
  }, [session]);

  useEffect(() => {
    if (!data?.offersEnabled || !session || isOwner || negotiatingMine || hasAutogeneratedDraft.current) return;
    setMessageInput(generatedDraft);
    hasAutogeneratedDraft.current = true;
  }, [data?.offersEnabled, session, isOwner, negotiatingMine, generatedDraft]);

  useEffect(() => {
    if (negotiatingMine) setShowCreateForm(false);
  }, [negotiatingMine]);

  if (listingType !== LISTING_TYPE.SALE) return null;

  if (isPending || !data) {
    return (
      <div className="mt-4 border-t border-gray-100 pt-4">
        <div className="h-24 animate-pulse rounded-lg bg-gray-100" aria-hidden />
      </div>
    );
  }

  if (isError) {
    return (
      <div className="mt-4 border-t border-gray-100 pt-4">
        <p className="text-sm text-red-600">{(error as Error)?.message}</p>
      </div>
    );
  }

  const { offersEnabled, listingPrice, offers } = data;
  const legalNameReady = buyerDetails.legalName.trim().length > 0;

  return (
    <div className="mt-4 border-t border-gray-100 pt-4">
      <h4 className="text-sm font-semibold text-gray-900">Professional offers</h4>
      <p className="mt-1 text-xs text-gray-500">
        A professional offer is a formal written intent to purchase. This draft includes buyer legal name, property description, location,
        and key terms you can edit before sending.
      </p>

      {!offersEnabled && (
        <p className="mt-2 text-sm text-gray-600">
          Offers are not enabled for this listing (must be active, for sale, and listed by a verified account).
        </p>
      )}

      {offersEnabled && status === 'unauthenticated' && !isOwner && (
        <p className="mt-3 text-sm text-gray-700">
          <Link href={`/auth/signin?callbackUrl=/listings/${listingId}`} className="font-medium text-primary-600 hover:underline">
            Sign in
          </Link>{' '}
          to send a professional offer.
        </p>
      )}

      {offersEnabled && session && !isOwner && (
        <div className="mt-3 rounded-lg border border-gray-200 bg-gray-50 p-3">
          {!negotiatingMine && (
            <>
              <p className="text-xs text-gray-600">Asking price: {formatNgn(listingPrice)}</p>
              <div className="mt-3 rounded-md border border-gray-200 bg-white p-3">
                <p className="text-sm text-gray-700">Open a full-screen editor to review and adjust your offer letter before sending.</p>
                <button
                  type="button"
                  className="btn-primary mt-3 w-full sm:w-auto"
                  onClick={() => setShowCreateForm(true)}
                >
                  Give an offer
                </button>
              </div>
            </>
          )}
          {negotiatingMine && (
            <div className="space-y-2 text-sm">
              <p>
                Current offer on the table: <span className="font-semibold text-gray-900">{formatNgn(negotiatingMine.amount)}</span>
              </p>
              <p className="text-xs text-gray-600">
                {negotiatingMine.turn === 'seller'
                  ? 'Waiting for the seller to respond.'
                  : 'The seller countered — you can send a new counter or maintain your previous offer.'}
              </p>
              {negotiatingMine.turn === 'buyer' && (
                <>
                  <label className="mt-2 block text-xs font-medium text-gray-700">Your counter (NGN)</label>
                  <input
                    type="text"
                    inputMode="decimal"
                    className="input mt-1 w-full"
                    value={counterByOffer[negotiatingMine._id] ?? ''}
                    onChange={(e) =>
                      setCounterByOffer((m) => ({ ...m, [negotiatingMine._id]: e.target.value.replace(/[^\d.]/g, '') }))
                    }
                  />
                  <label className="mt-2 block text-xs font-medium text-gray-700">Note (optional)</label>
                  <textarea
                    className="input mt-1 min-h-[56px] w-full resize-y"
                    maxLength={1000}
                    value={counterMsgByOffer[negotiatingMine._id] ?? ''}
                    onChange={(e) =>
                      setCounterMsgByOffer((m) => ({ ...m, [negotiatingMine._id]: e.target.value }))
                    }
                  />
                  <div className="mt-2 flex flex-col gap-2 sm:flex-row">
                    <button
                      type="button"
                      className="btn-primary flex-1"
                      disabled={
                        patchOffer.isPending || !(Number(String(counterByOffer[negotiatingMine._id] ?? '').replace(/,/g, '')) > 0)
                      }
                      onClick={() => {
                        const raw = counterByOffer[negotiatingMine._id] ?? '';
                        const amount = Number(String(raw).replace(/,/g, ''));
                        patchOffer.mutate({
                          offerId: negotiatingMine._id,
                          body: {
                            action: 'counter',
                            amount,
                            message: (counterMsgByOffer[negotiatingMine._id] ?? '').trim() || undefined,
                          },
                        });
                      }}
                    >
                      Send counter
                    </button>
                    <button
                      type="button"
                      className="btn-secondary flex-1"
                      disabled={patchOffer.isPending}
                      onClick={() => patchOffer.mutate({ offerId: negotiatingMine._id, body: { action: 'maintain' } })}
                    >
                      Maintain my offer of {formatNgn(negotiatingMine.maintainAmount ?? negotiatingMine.amount)}
                    </button>
                  </div>
                </>
              )}
              {patchOffer.isError && (
                <p className="text-xs text-red-600">{(patchOffer.error as Error)?.message}</p>
              )}
            </div>
          )}
        </div>
      )}
      {offersEnabled && session && !isOwner && !negotiatingMine && showCreateForm && (
        <div className="fixed inset-0 z-50 flex flex-col bg-white" role="dialog" aria-modal="true" aria-labelledby="offer-editor-title">
          <div className="border-b border-gray-200 bg-white px-4 py-3 sm:px-6">
            <div className="mx-auto flex w-full max-w-5xl items-center justify-between gap-3">
              <div>
                <h5 id="offer-editor-title" className="text-base font-semibold text-gray-900">
                  Offer letter editor
                </h5>
                <p className="text-xs text-gray-500">Review buyer details and edit your professional offer before sending.</p>
              </div>
              <button type="button" className="btn-secondary" onClick={() => setShowCreateForm(false)}>
                Close
              </button>
            </div>
          </div>
          <div className="min-h-0 flex-1 overflow-y-auto bg-gray-50 px-4 py-4 sm:px-6">
            <div className="mx-auto w-full max-w-5xl space-y-3 rounded-lg border border-gray-200 bg-white p-4 shadow-sm sm:p-5">
              <p className="text-xs text-gray-600">Asking price: {formatNgn(listingPrice)}</p>
              <div className="rounded-md border border-gray-200 bg-gray-50 p-3">
                <h5 className="text-xs font-semibold uppercase tracking-wide text-gray-700">Buyer details</h5>
                <div className="mt-2 grid gap-2 sm:grid-cols-2">
                  <div className="sm:col-span-2">
                    <label className="block text-xs font-medium text-gray-700">Legal name *</label>
                    <input
                      type="text"
                      className="input mt-1 w-full"
                      placeholder="e.g. Amina O. Adeyemi"
                      value={buyerDetails.legalName}
                      onChange={(e) => setBuyerDetails((prev) => ({ ...prev, legalName: e.target.value }))}
                    />
                  </div>
                  <div>
                    <label className="block text-xs font-medium text-gray-700">Email</label>
                    <input
                      type="email"
                      className="input mt-1 w-full"
                      placeholder="name@email.com"
                      value={buyerDetails.email}
                      onChange={(e) => setBuyerDetails((prev) => ({ ...prev, email: e.target.value }))}
                    />
                  </div>
                  <div>
                    <label className="block text-xs font-medium text-gray-700">Phone</label>
                    <input
                      type="text"
                      className="input mt-1 w-full"
                      placeholder="e.g. +2348012345678"
                      value={buyerDetails.phone}
                      onChange={(e) => setBuyerDetails((prev) => ({ ...prev, phone: e.target.value }))}
                    />
                  </div>
                  <div className="sm:col-span-2">
                    <label className="block text-xs font-medium text-gray-700">Address</label>
                    <input
                      type="text"
                      className="input mt-1 w-full"
                      placeholder="Your legal/correspondence address"
                      value={buyerDetails.address}
                      onChange={(e) => setBuyerDetails((prev) => ({ ...prev, address: e.target.value }))}
                    />
                  </div>
                </div>
              </div>
              <label className="block text-xs font-medium text-gray-700">Your offer (NGN)</label>
              <input
                type="text"
                inputMode="decimal"
                className="input w-full"
                placeholder="e.g. 45000000"
                value={amountInput}
                onChange={(e) => setAmountInput(e.target.value.replace(/[^\d.]/g, ''))}
              />
              <div className="grid gap-2 sm:grid-cols-2">
                <div>
                  <label className="block text-xs font-medium text-gray-700">Preferred completion timeline</label>
                  <input
                    type="text"
                    className="input mt-1 w-full"
                    placeholder="e.g. 30 days from acceptance"
                    value={buyerDetails.completionTimeline}
                    onChange={(e) => setBuyerDetails((prev) => ({ ...prev, completionTimeline: e.target.value }))}
                  />
                </div>
                <div>
                  <label className="block text-xs font-medium text-gray-700">Additional terms</label>
                  <input
                    type="text"
                    className="input mt-1 w-full"
                    placeholder="e.g. Subject to mortgage approval"
                    value={buyerDetails.additionalTerms}
                    onChange={(e) => setBuyerDetails((prev) => ({ ...prev, additionalTerms: e.target.value }))}
                  />
                </div>
              </div>
              <div className="flex items-center justify-between gap-3">
                <label className="block text-xs font-medium text-gray-700">Offer letter (editable)</label>
                <span className="text-[11px] text-gray-500">{messageInput.length}/1000</span>
              </div>
              <textarea
                className="input min-h-[280px] w-full resize-y"
                maxLength={1000}
                value={messageInput}
                onChange={(e) => setMessageInput(e.target.value)}
              />
              <div className="flex flex-col gap-2 sm:flex-row sm:items-center sm:justify-between">
                <button
                  type="button"
                  className="text-xs font-medium text-primary-600 hover:underline"
                  onClick={() => setMessageInput(generatedDraft)}
                >
                  Refresh auto-generated offer letter
                </button>
                <div className="flex gap-2">
                  <button type="button" className="btn-secondary" onClick={() => setShowCreateForm(false)}>
                    Cancel
                  </button>
                  <button
                    type="button"
                    className="btn-primary"
                    disabled={createOffer.isPending || !amountInput || !legalNameReady}
                    onClick={() => createOffer.mutate()}
                  >
                    {createOffer.isPending ? 'Sending...' : 'Send professional offer'}
                  </button>
                </div>
              </div>
              {!legalNameReady && <p className="text-xs text-amber-700">Enter your legal name to send a professional offer.</p>}
              {createOffer.isError && <p className="text-xs text-red-600">{(createOffer.error as Error)?.message}</p>}
            </div>
          </div>
        </div>
      )}

      {isOwner && offers.length > 0 && (
        <ul className="mt-3 space-y-3">
          {offers.map((o) => (
            <li key={o._id} className="rounded-lg border border-gray-200 bg-white p-3 text-sm shadow-sm">
              <div className="flex flex-wrap items-baseline justify-between gap-2">
                <span className="font-medium text-gray-900">
                  {o.buyer?._id ? (
                    <Link href={`/authors/${o.buyer._id}`} className="text-primary-600 hover:underline">
                      {toFirstName(o.buyer.firstName, o.buyer.name, 'Buyer')}
                    </Link>
                  ) : (
                    'Buyer'
                  )}
                </span>
                <span
                  className={`rounded-full px-2 py-0.5 text-xs font-semibold ${
                    o.status === 'negotiating'
                      ? 'bg-amber-100 text-amber-800'
                      : o.status === 'accepted'
                        ? 'bg-emerald-100 text-emerald-800'
                        : 'bg-gray-100 text-gray-700'
                  }`}
                >
                  {o.status}
                </span>
              </div>
              <p className="mt-1 text-gray-700">
                Offer: <span className="font-semibold">{formatNgn(o.amount)}</span>
                {o.status === 'negotiating' && (
                  <span className="ml-2 text-xs text-gray-500">
                    {o.turn === 'seller' ? '(your move)' : '(awaiting buyer)'}
                  </span>
                )}
              </p>
              {o.status === 'negotiating' && o.turn === 'seller' && (
                <div className="mt-2 space-y-2 border-t border-gray-100 pt-2">
                  <div className="flex flex-wrap gap-2">
                    <button
                      type="button"
                      className="btn-primary text-sm"
                      disabled={patchOffer.isPending}
                      onClick={() => patchOffer.mutate({ offerId: o._id, body: { action: 'accept' } })}
                    >
                      Accept
                    </button>
                    <button
                      type="button"
                      className="btn-secondary text-sm"
                      disabled={patchOffer.isPending}
                      onClick={() => patchOffer.mutate({ offerId: o._id, body: { action: 'decline' } })}
                    >
                      Decline
                    </button>
                  </div>
                  {!o.sellerCounterLocked ? (
                    <>
                      <label className="block text-xs font-medium text-gray-700">Counter amount (NGN)</label>
                      <input
                        type="text"
                        inputMode="decimal"
                        className="input w-full"
                        placeholder="Counter price"
                        value={counterByOffer[o._id] ?? ''}
                        onChange={(e) => setCounterByOffer((m) => ({ ...m, [o._id]: e.target.value.replace(/[^\d.]/g, '') }))}
                      />
                      <label className="block text-xs font-medium text-gray-700">Note (optional)</label>
                      <textarea
                        className="input min-h-[56px] w-full resize-y"
                        maxLength={1000}
                        value={counterMsgByOffer[o._id] ?? ''}
                        onChange={(e) => setCounterMsgByOffer((m) => ({ ...m, [o._id]: e.target.value }))}
                      />
                      <button
                        type="button"
                        className="btn-secondary w-full text-sm"
                        disabled={patchOffer.isPending || !(Number(String(counterByOffer[o._id] ?? '').replace(/,/g, '')) > 0)}
                        onClick={() => {
                          const amount = Number(String(counterByOffer[o._id] ?? '').replace(/,/g, ''));
                          patchOffer.mutate({
                            offerId: o._id,
                            body: {
                              action: 'counter',
                              amount,
                              message: (counterMsgByOffer[o._id] ?? '').trim() || undefined,
                            },
                          });
                        }}
                      >
                        Send counter-offer
                      </button>
                    </>
                  ) : (
                    <p className="text-xs text-amber-700">
                      Buyer maintained their offer at {formatNgn(o.amount)}. You can accept or decline only.
                    </p>
                  )}
                </div>
              )}
            </li>
          ))}
        </ul>
      )}

      {isOwner && offers.length === 0 && offersEnabled && (
        <p className="mt-2 text-sm text-gray-500">No offers yet. Buyers with accounts will see the option to send one here.</p>
      )}

      {!isOwner && offersEnabled && session && negotiatingMine === null && offers.some((o) => o.status !== 'negotiating') && (
        <p className="mt-2 text-xs text-gray-500">
          <button type="button" className="text-primary-600 hover:underline" onClick={() => refetch()}>
            Refresh
          </button>{' '}
          to see past offers.
        </p>
      )}
    </div>
  );
}
